# Generated by Django 4.2.28 on 2026-03-02 03:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, help_text='Height in inches', null=True, validators=[django.core.validators.MinValueValidator(36), django.core.validators.MaxValueValidator(96)])),
                ('activity_level', models.IntegerField(blank=True, help_text='Your activity level on a scale of 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dietary_preferences', models.CharField(blank=True, help_text='e.g., Vegetarian, Vegan, Gluten-free', max_length=100, null=True)),
                ('favorite_stores', models.CharField(blank=True, help_text='List of favorite grocery stores (comma seperated)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
