# Generated by Django 4.2.28 on 2026-03-02 05:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Grocery List', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Monday of the planned week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Is this the user's current plan?")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the recipe', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the recipe')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='dinner', max_length=20)),
                ('prep_time_minutes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('cook_time_minutes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('nutrition', models.JSONField(default=dict, help_text="JSON data: {'calories': 450, 'protein': 25, 'carbs': 50, 'fat': 15}")),
                ('dietary_tags', models.JSONField(default=list, help_text='List of dietary tags')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Step-by-step cooking instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('chain', models.CharField(blank=True, help_text="Store chain (e.g., 'Walmart')", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ingredient name (e.g., 'flour')", max_length=100)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('metric', models.CharField(help_text="Unit (e.g., 'cups', 'tbsp', 'g')", max_length=20)),
                ('category', models.CharField(blank=True, help_text="e.g., 'produce', 'dairy'", max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='planner.recipe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroceryListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('metric', models.CharField(max_length=20)),
                ('price_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('grocery_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.grocerylist')),
                ('source_recipes', models.ManyToManyField(blank=True, to='planner.recipe')),
                ('suggested_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.store')),
            ],
            options={
                'ordering': ['ingredient_name'],
            },
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='meal_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_list', to='planner.mealplan'),
        ),
        migrations.CreateModel(
            name='StoreIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_unit', models.CharField(default='each', help_text="'per lb', 'per item', etc.", max_length=20)),
                ('in_stock', models.BooleanField(default=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='planner.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'in_stock'], name='planner_sto_store_i_7a55d3_idx')],
                'unique_together': {('store', 'ingredient_name', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('custom_notes', models.TextField(blank=True, help_text='User notes for this meal')),
                ('was_completed', models.BooleanField(default=False, help_text='Did the user actually eat this?')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='planner.mealplan')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.recipe')),
            ],
            options={
                'ordering': ['day_of_week', 'meal_type'],
                'unique_together': {('meal_plan', 'day_of_week', 'meal_type')},
            },
        ),
    ]
