# Generated by Django 4.2 on 2026-03-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_mealplan_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeingredient',
            options={'ordering': ['ingredient_name']},
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., produce, dairy', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='metric',
            field=models.CharField(help_text='Unit', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(help_text='Ingredient name', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='chain',
            field=models.CharField(blank=True, help_text='Store chain', max_length=50),
        ),
        migrations.AlterField(
            model_name='storeingredient',
            name='price_unit',
            field=models.CharField(default='each', help_text="'per lb', 'each', etc.", max_length=20),
        ),
    ]
