# Generated by Django 4.2 on 2026-03-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_storeingredient_options_store_latitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grocerylistitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
